# Generated by Django 5.0.1 on 2024-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_stock_scraper_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
