# Generated by Django 6.0.1 on 2026-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_stock_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('total_value_gbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value_currency_index', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hd_value_gbp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hd_value_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hd_value_currency_index', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gbp_usd_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('currency_index_rate', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name': 'Daily Snapshot',
                'verbose_name_plural': 'Daily Snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
