# Generated by Django 6.0.3 on 2026-05-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_transaction_price_alter_transaction_tcost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricPrice',
        ),
    ]
